### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by Chrisly3ear** [Admin9705/The-Awesome-Plex-Server#1]
Hi,

I read your thread on reddit. May I suggest to incorporate some form of encryption, because you cannot be sure that Google (or any other cloud storage provider) doesn't keep a spare key to your data.

Encfs (https://vgough.github.io/encfs/) is a popular, easy to setup and secure solution you could use. You could enrypt the data folder(s) and only sync their encrypted version. Idk if PlexDrive will play nice with this.

Here's a writeup I found: https://medium.com/@privatewahts/building-an-infinite-plex-media-server-using-amazon-cloud-drive-for-average-computer-users-d16caab62d14
This person uses Amazon Cloud Drive, but the encryption part applies regardless of the storage solution.

Chris

**Comment by Admin9705** [comment]
Haha thank you, i didn't expect a comment here so fast.  I write up the whole thing here first; make sure it works then add the encryption.

**Comment by alternativesurfer** [comment]
+1

Came here to comment about encryption as well.
Would hate to lose my unlimited Google Drive account.

**Comment by Admin9705** [comment]
Fully agree, burnt writing and testing this over the last 30 days, i swear at least 5 hours each day.  Will take a break because it's working and security hardening is next focus.

**Comment by Admin9705** [comment]
Posted that users are responsible for encryption.  If you have a solution, modify the guide and send the instructions.  Will test and add and give proper credit.  Do not have time to make major modifications and agree it's important.  I personally do not have a problem with this; risk management.
