### ISSUE TITLE
radarr cant find movies on cloud

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/The-Awesome-Plex-Server#11]
i made a new server using a dedicated server and now radarr cant see movies in g drive. couch potato can, also  plex but not radarr. sonarr can see tv shows

**Comment by Admin9705** [comment]
@daveftw84 , i'll look into on next test run

**Comment by daveftw84** [comment]
i fixed it by using same local.rc as last server

**Comment by daveftw84** [comment]
sh /opt/postyml.sh &

is the only thing explained to add to the rc.local file now.
before, there is a few others

**Comment by Admin9705** [comment]
great job dave, i'll make the update.  that's what i'm talking about!
