### ISSUE TITLE
reporting couch potato errors on log

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/The-Awesome-Plex-Server#13]
09-11 08:03:30 ERROR
[to.core.media.movie._base] Failed update media: Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/media/movie/_base/main.py", line 312, in update db.update(media) File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner res = f(*args, **kwargs) File "/app/couchpotato/libs/CodernityDB/database.py", line 917, in update _id, new_rev = self._update_indexes(_rev, data) File "/app/couchpotato/libs/CodernityDB/database.py", line 678, in _update_indexes _id, new_rev, db_data = self._update_id_index(_rev, data) File "/app/couchpotato/libs/CodernityDB/database.py", line 666, in _update_id_index raise RevConflict() RevConflict
09-11 08:03:42 ERROR
[to.core.media.movie._base] Failed update media: Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/media/movie/_base/main.py", line 312, in update db.update(media) File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner res = f(*args, **kwargs) File "/app/couchpotato/libs/CodernityDB/database.py", line 917, in update _id, new_rev = self._update_indexes(_rev, data) File "/app/couchpotato/libs/CodernityDB/database.py", line 678, in _update_indexes _id, new_rev, db_data = self._update_id_index(_rev, data) File "/app/couchpotato/libs/CodernityDB/database.py", line 666, in _update_id_index raise RevConflict() RevConflict
09-11 09:07:22 ERROR
[tato.core.plugins.renamer] Couldn't move file "/sabcomplete/It's A Wonderful Life 1946 BW BRRip 720p AC3 x264 mkv/It's A Wonderful Life 1946 BW BRRip 720p AC3 x264.mkv" to "/movies/It's a Wonderful Life (1946)/It's a Wonderful Life.mkv": Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: "/sabcomplete/It's A Wonderful Life 1946 BW BRRip 720p AC3 x264 mkv/It's A Wonderful Life 1946 BW BRRip 720p AC3 x264.mkv"
09-11 09:07:22 ERROR
[tato.core.plugins.renamer] Failed renaming the file "It's A Wonderful Life 1946 BW BRRip 720p AC3 x264.mkv" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 641, in scan self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group)) File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: "/sabcomplete/It's A Wonderful Life 1946 BW BRRip 720p AC3 x264 mkv/It's A Wonderful Life 1946 BW BRRip 720p AC3 x264.mkv"
09-11 10:23:34 ERROR
[hpotato.core.plugins.base] Couldn't remove empty directory /sabcomplete/Se7en 1995 1080p BluRay DTS-HD x264-BARC0DE: Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/base.py", line 151, in deleteEmptyFolder os.rmdir(folder) OSError: [Errno 39] Directory not empty: '/sabcomplete/Se7en 1995 1080p BluRay DTS-HD x264-BARC0DE'
09-11 10:23:43 ERROR
[tato.core.plugins.renamer] Couldn't move file "/sabcomplete/Goodfellas 1990 1080p BluRay 25th Anniversary DTS-HD MA 5 1 x264-BluEvo-Obfuscated/18tfWs5iDG3Gd6kAzFZesMQ.mkv" to "/movies/GoodFellas (1990)/GoodFellas.mkv": Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/Goodfellas 1990 1080p BluRay 25th Anniversary DTS-HD MA 5 1 x264-BluEvo-Obfuscated/18tfWs5iDG3Gd6kAzFZesMQ.mkv'
09-11 10:23:43 ERROR
[tato.core.plugins.renamer] Failed renaming the file "18tfWs5iDG3Gd6kAzFZesMQ.mkv" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 641, in scan self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group)) File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/Goodfellas 1990 1080p BluRay 25th Anniversary DTS-HD MA 5 1 x264-BluEvo-Obfuscated/18tfWs5iDG3Gd6kAzFZesMQ.mkv'
09-11 10:23:51 ERROR
[tato.core.plugins.renamer] Couldn't move file "/sabcomplete/Saving Private Ryan 1998 1080p Bluray X264-BARC0DE/Saving.Private.Ryan.1998.1080p.Bluray.X264-BARC0DE.mkv" to "/movies/Saving Private Ryan (1998)/Saving Private Ryan.mkv": Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/Saving Private Ryan 1998 1080p Bluray X264-BARC0DE/Saving.Private.Ryan.1998.1080p.Bluray.X264-BARC0DE.mkv'
09-11 10:23:51 ERROR
[tato.core.plugins.renamer] Failed renaming the file "Saving.Private.Ryan.1998.1080p.Bluray.X264-BARC0DE.mkv" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 641, in scan self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group)) File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/Saving Private Ryan 1998 1080p Bluray X264-BARC0DE/Saving.Private.Ryan.1998.1080p.Bluray.X264-BARC0DE.mkv'
09-11 13:42:32 ERROR
[tato.core.plugins.renamer] Couldn't move file "/sabcomplete/Life Is Beautiful 1997 720p BluRay x264/Life.Is.Beautiful.1997.720p.BluRay.x264.AC3-FuzerHD.mkv" to "/movies/Life Is Beautiful (1997)/Life Is Beautiful.mkv": Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/Life Is Beautiful 1997 720p BluRay x264/Life.Is.Beautiful.1997.720p.BluRay.x264.AC3-FuzerHD.mkv'
09-11 13:42:32 ERROR
[tato.core.plugins.renamer] Failed renaming the file "Life.Is.Beautiful.1997.720p.BluRay.x264.AC3-FuzerHD.mkv" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 641, in scan self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group)) File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/Life Is Beautiful 1997 720p BluRay x264/Life.Is.Beautiful.1997.720p.BluRay.x264.AC3-FuzerHD.mkv'
09-11 13:42:39 ERROR
[tato.core.plugins.renamer] Couldn't move file "/sabcomplete/city of god 2002 proper 1080p bluray x264-phobos/City.of.God.2002.PROPER.1080p.BluRay.x264-PHOBOS.mkv" to "/movies/City of God (2002)/City of God.mkv": Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/city of god 2002 proper 1080p bluray x264-phobos/City.of.God.2002.PROPER.1080p.BluRay.x264-PHOBOS.mkv'
09-11 13:42:39 ERROR
[tato.core.plugins.renamer] Failed renaming the file "City.of.God.2002.PROPER.1080p.BluRay.x264-PHOBOS.mkv" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 641, in scan self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group)) File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/city of god 2002 proper 1080p bluray x264-phobos/City.of.God.2002.PROPER.1080p.BluRay.x264-PHOBOS.mkv'
09-11 13:42:42 ERROR
[tato.core.plugins.renamer] Couldn't move file "/sabcomplete/Star Wars Episode IV A New Hope 1977 1080p BluRay DTS x264-CyTSuNee/eeNuSTyC-462x.STD.yaRulB.p0801.7791.epoH.weN.A.VI.edosipE.sraW.ratS.mkv" to "/movies/Star Wars (1977)/Star Wars.mkv": Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/Star Wars Episode IV A New Hope 1977 1080p BluRay DTS x264-CyTSuNee/eeNuSTyC-462x.STD.yaRulB.p0801.7791.epoH.weN.A.VI.edosipE.sraW.ratS.mkv'
09-11 13:42:42 ERROR
[tato.core.plugins.renamer] Failed renaming the file "eeNuSTyC-462x.STD.yaRulB.p0801.7791.epoH.weN.A.VI.edosipE.sraW.ratS.mkv" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 641, in scan self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group)) File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/Star Wars Episode IV A New Hope 1977 1080p BluRay DTS x264-CyTSuNee/eeNuSTyC-462x.STD.yaRulB.p0801.7791.epoH.weN.A.VI.edosipE.sraW.ratS.mkv'
09-11 13:43:18 ERROR
[tato.core.plugins.scanner] Couldn't find any movie files for the good bad and ugly 1966 multi
09-11 13:43:29 ERROR
[hpotato.core.plugins.base] Failed opening url in OMDBAPI: https://www.omdbapi.com/?apikey=xxx&type=movie&y=2006&t=eenustyc+462x+3ca+std+yarulb+p0801+6002+detraped+eht Traceback (most recent call last): ReadTimeout: HTTPSConnectionPool(host='www.omdbapi.com', port=443): Read timed out. (read timeout=3)
09-11 14:17:32 ERROR
[tato.core.plugins.renamer] Couldn't move file "/sabcomplete/Guardians of the Galaxy 2014 720p BluRay DTS x264-HiDt cp(tt2015381)/owOVmTBeBCNYc9coQSGbvBDVG23HxP8UJVVeB.mkv" to "/movies/Guardians of the Galaxy (2014)/Guardians of the Galaxy.mkv": Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 836, in moveFile raise Exception('Destination "%s" already exists' % dest) Exception: Destination "/movies/Guardians of the Galaxy (2014)/Guardians of the Galaxy.mkv" already exists
09-11 14:17:32 ERROR
[tato.core.plugins.renamer] Failed renaming the file "owOVmTBeBCNYc9coQSGbvBDVG23HxP8UJVVeB.mkv" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 641, in scan self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group)) File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 836, in moveFile raise Exception('Destination "%s" already exists' % dest) Exception: Destination "/movies/Guardians of the Galaxy (2014)/Guardians of the Galaxy.mkv" already exists
09-11 15:10:52 ERROR
[tato.core.plugins.renamer] Couldn't move file "/sabcomplete/Apocalypse Now (1979) BluRay 1080p x264 mkv/5otyUD5q4iFvy4tAn.mkv" to "/movies/Apocalypse Now (1979)/Apocalypse Now.mkv": Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/Apocalypse Now (1979) BluRay 1080p x264 mkv/5otyUD5q4iFvy4tAn.mkv'
09-11 15:10:52 ERROR
[tato.core.plugins.renamer] Failed renaming the file "5otyUD5q4iFvy4tAn.mkv" : Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 641, in scan self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group)) File "/app/couchpotato/couchpotato/core/plugins/renamer.py", line 845, in moveFile shutil.move(old, dest) File "/usr/lib/python2.7/shutil.py", line 302, in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 130, in copy2 copyfile(src, dst) File "/usr/lib/python2.7/shutil.py", line 82, in copyfile with open(src, 'rb') as fsrc: IOError: [Errno 2] No such file or directory: '/sabcomplete/Apocalypse Now (1979) BluRay 1080p x264 mkv/5otyUD5q4iFvy4tAn.mkv'
09-11 15:47:41 ERROR
[31mEBML entity not found, bad file format
09-11 15:50:47 ERROR
[tato.core.plugins.scanner] Couldn't find any movie files for the big sick 2017
09-11 15:51:39 ERROR
[hpotato.core.plugins.base] Failed opening url in OMDBAPI: https://www.omdbapi.com/?apikey=xxx&type=movie&y=2008&t=zack+and+miri+make+a+porno Traceback (most recent call last): ReadTimeout: HTTPSConnectionPool(host='www.omdbapi.com', port=443): Read timed out. (read timeout=3)
09-11 17:32:03 ERROR
[hpotato.core.plugins.base] Couldn't remove empty directory /sabcomplete/The Prestige 2006 1080p BluRay DTS x264-CyTSuNee: Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/base.py", line 151, in deleteEmptyFolder os.rmdir(folder) OSError: [Errno 39] Directory not empty: '/sabcomplete/The Prestige 2006 1080p BluRay DTS x264-CyTSuNee'

**Comment by Admin9705** [comment]
i know this sounds crazy, but have you rebooted your server?

On a second note, have you tried going to http://ipv4address:9000, select couchpototo container, console and then look for the sabcomplete folder and then look in there and see if you see the movies?
