### ISSUE TITLE
Plex DVR

### ISSUE THREAD

**Issue by cmannes** [Admin9705/The-Awesome-Plex-Server#14]
So, I've been slowly setting things up using your guide.  Both as a learning experience and to cloudify my existing plex setup.  Have you given any thoughts to adding Plex DVR functionality?  My impression isn't that it wouldn't be too difficult, but before I wing it on my own, I thought I'd ask.

**Comment by Admin9705** [comment]
Well, the DVR I run is on my home server.  This setup is for a REMOTE SERVER that's distance... so I don't think the DVR would work remotely.  If configuring this at the house, that's easy to enable.  Only downside is it's on linux.

**Comment by cmannes** [comment]
Ah..  I'm using your instructions but on a local ubuntu server.  My guess is that I'd want to DVR to one location, and then later shift it to the GDrive location.   Perhaps with a transcode of some sort in the middle.  I'll do some further learning & research.  Thanks!

**Comment by Admin9705** [comment]
You can use a windows machine local and have it save to google file stream
drive, which then you make a tv folder on the Ubuntu server and scan that
location of your google drive. Actually did it and works, but original DVR
needs to be local. My setup is just baseline here you go Plex server and
download materials to make it run.

**Comment by daveftw84** [comment]
something like this be cool
https://www.reddit.com/r/PleX/comments/6ezan8/how_to_make_plex_live_tv_work_with_iptv_or_any/
