### ISSUE TITLE
need help please

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/The-Awesome-Plex-Server#15]
im willing to pay you if you can help me with a simple script.

**Comment by Admin9705** [comment]
Dave, I currently have an insane job and do this as a hobby project.  I struggle with linux myself and just spent 10 hours on making minor modifications.  You might want to hit a linux forum up or project for hire on this stuff.  I am learning on the go.  My works is mostly instructions and not a series of scripts.

**Comment by daveftw84** [comment]
can you just look at
 cd "$spath"
#reals=$( wget "http://auth.smoothstreams.tv/reporter.php?m=$mac&m2=$wmac&f=$fw" --user-agent="$ua" -O- -q);
echo "reals=$reals"
#sprtacc=$( wget "http://sportsaccess.se/dash/origin.php?m=$mac&m2=$wmac&f=$fw" --user-agent="$ua" -O- -q);
echo "sprtacc=$sprtacc"
#nohup curl -A "$ua" "http://auth.smoothstreams.tv/reporter.php?m=$mac&m2=$wmac&f=$fw" &
#nohup curl -A "$ua" "http://sportsaccess.se/dash/reporter.php?m=$mac&m2=$wmac&f=$fw" &

what is the -O- and -q doing?
or the echo?

i know the script is working just i cant figure out everything thats being sent... 
i have the fw, and useragent already and this authorizes any mac given . i can share everything with you and pay you on top. i know this script is childs play for you. 

here is an example of what i have excluding useragent, what am i missing?
http://sportsaccess.se/dash/origin.php?m=00:11:63:02:3b:23&m2=&f=S4.20161207.V8.0.2

**Comment by Admin9705** [comment]
Sorry man, I have no idea at all. I not really that versed in Linux. I only
know what I need to know.

**Comment by Admin9705** [comment]
Is -q for quiet? Only thing I know.
