### ISSUE TITLE
03 - RClone - UnionFS Sync & Move

### ISSUE THREAD

**Issue by Deiteq** [Admin9705/The-Awesome-Plex-Server#19]
Hi again, think that I've finally figured out the encryption  method but before sending my edits I wanted to ask about the cron job part from line 140.
Do we still need to use `crontab -e` and set a time for them like on one of your earlier versions or are they automatic now since you've changed that part?

> Line 140 # Press CTRL+X and ENTER; creating a CRONJOB as ROOT

Thanks in advance.

**Comment by Admin9705** [comment]
@Deiteq , check out the comment on the pull request.  fixed the issue, so see if it works :D
