### ISSUE TITLE
plex py 

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/The-Awesome-Plex-Server#24]
im having issues with plex py installation .

im running 
git clone https://github.com/JonnyWong16/plexpy.git
python PlexPy.py
 
but with sudo, since without sudo, gives me permission errors
but sudo python PlexPy.py 
is stalling out 

anontv@Ubuntu-1604-xenial-64-nextcloud:/opt/plexpy$ sudo python PlexPy.py
2017-10-03 22:14:36 - INFO :: MainThread : Checking to see if the database has all tables....
2017-10-03 22:14:36 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /opt/plexpy
2017-10-03 22:14:36 - DEBUG :: MainThread : Git output: cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
2017-10-03 22:14:36 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /opt/plexpy
2017-10-03 22:14:36 - DEBUG :: MainThread : Git output: master
2017-10-03 22:14:36 - INFO :: MainThread : Retrieving latest version information from GitHub
2017-10-03 22:14:36 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
2017-10-03 22:14:37 - DEBUG :: MainThread : Latest version is cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
2017-10-03 22:14:37 - INFO :: MainThread : PlexPy is up to date
2017-10-03 22:14:37 - INFO :: MainThread : Scheduled background task: Check GitHub for updates
2017-10-03 22:14:37 - INFO :: MainThread : Scheduled background task: Backup PlexPy database
2017-10-03 22:14:37 - INFO :: MainThread : Scheduled background task: Backup PlexPy config
2017-10-03 22:14:37 - INFO :: MainThread : PlexPy WebStart :: Starting PlexPy web server on http://0.0.0.0:8181/

**Comment by daveftw84** [comment]
stuck at 
2017-10-03 22:14:37 - INFO :: MainThread : PlexPy WebStart :: Starting PlexPy web server on http://0.0.0.0:8181/

**Comment by daveftw84** [comment]
should i try again as root?

**Comment by daveftw84** [comment]
sudo systemctl enable plexpy.service
gives me invalid argument

**Comment by Admin9705** [comment]
I'll check this weekend Dave!  I haven't put plex py on the test vm, but shouldn't be a hard fix. everything else working?

**Comment by daveftw84** [comment]
ya, move service stalls out some times, most of the time stopping and starting the service fixes it.
butt right now its stuck at 
Oct 05 03:38:46 Ubuntu-1604-xenial-64-nextcloud systemd[1]: Stopping Move Service Daemon...
Oct 05 03:38:46 Ubuntu-1604-xenial-64-nextcloud systemd[1]: Stopped Move Service Daemon.
after restarting the service off and on. might have to restart the server

**Comment by daveftw84** [comment]
Oct 05 03:36:32 Ubuntu-1604-xenial-64-nextcloud bash[29035]: 2017/10/05 03:36:32 INFO  : Google drive root '': Waiting for checks to finish
Oct 05 03:36:32 Ubuntu-1604-xenial-64-nextcloud bash[29035]: 2017/10/05 03:36:32 INFO  : Google drive root '': Waiting for transfers to finish

**Comment by Admin9705** [comment]
might be that command i put. check out the restart option for the rclone service and see if that works. fixed rcleon and plexdrive.

**Comment by daveftw84** [comment]
RemainAfterExit=yes?

**Comment by daveftw84** [comment]
im sorry im confused. long day

**Comment by Admin9705** [comment]
@daveftw84 , see your getting smarter with linux day by day :D - I feel like i'm a 2 out 10 - 10 being the best on linux; so a one point bump :D

**Comment by daveftw84** [comment]
[Unit]
Description=PlexDrive4 Service
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/bin/plexdrive4 --uid=1001 --gid=1001 --fuse-options=allow_other --refresh-interval=1m /mnt/plexdrive4
TimeoutStopSec=20
KillMode=process
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

**Comment by daveftw84** [comment]
ive already added it the day you did xD

**Comment by daveftw84** [comment]
i check up for updates daily lol

**Comment by Admin9705** [comment]
oh plexpy runs in docker, so why the issues?

**Comment by daveftw84** [comment]
i gave up on the plex py for now

**Comment by daveftw84** [comment]
the move service is what im worried about

**Comment by Admin9705** [comment]
that one stalls?  might never stalls.

**Comment by daveftw84** [comment]
Oct 05 03:38:46 Ubuntu-1604-xenial-64-nextcloud systemd[1]: Stopping Move Service Daemon...
Oct 05 03:38:46 Ubuntu-1604-xenial-64-nextcloud systemd[1]: Stopped Move Service Daemon.
after restarting the service off and on. might have to restart the server

**Comment by daveftw84** [comment]
Ubuntu-1604-xenial-64-nextcloud bash[29035]: 2017/10/05 03:36:32 INFO : Google drive root '': Waiting for checks to finish
Oct 05 03:36:32 Ubuntu-1604-xenial-64-nextcloud bash[29035]: 2017/10/05 03:36:32 INFO : Google drive root '': Waiting for transfers to finish

**Comment by daveftw84** [comment]
ive restarted the service but it still says that 
restarting server now

**Comment by daveftw84** [comment]
youre always welcome in my server if you want to take a look at it

**Comment by daveftw84** [comment]
im very determined to this server

**Comment by daveftw84** [comment]
i just noticed you updated plexpy/docker
sorry i thought you were giving me a tip about the move service and i mixed it up.
restarted the server got move service back moving stuff. 
ill try out the plex py later tonight .  feel like this server is kicking my ass

**Comment by daveftw84** [comment]
for some reason i feel like things shouldnt be this difficult and im making it harder then it needs to be.
thanks for your patience

**Comment by daveftw84** [comment]
i notice the move service says it has 2 errors.
is this serious ?

**Comment by daveftw84** [comment]
Errors:                 2

**Comment by Admin9705** [comment]
it's linux, it's difficult lol. plus different varations, servers, and hardware doesn't help
