### ISSUE TITLE
rclone encrypted move.service

### ISSUE THREAD

**Issue by Deiteq** [Admin9705/The-Awesome-Plex-Server#28]
For those that may be struggling with uploading to the encrypted gdrive, I made a new pull request as needed to add another encrypted rclone mount due to plexdrive mount being unable to write to gdrive.

Basically need to go back into `rclone config` add `gdrive` (with option 8) like in the unencrypted instructions and a new encrypted mount (option 5), name it `gcrypt` or whatever you like then point it to `gdrive:/encrypt` (encrypt being the name of your encrypted folder and use the same password and salt as before), then change the `rclone-move.sh` from `crypt:/` to `gcrypt:/` and add a new `rclone.service` (copy the old one and rename it to `rclone-crypt.service`) as well as `mkdir /mnt/rclone-crypt` and finally have `gcrypt` point to `/mnt/rclone-crypt`.
This way you should have the `unionfs.service` still use the plexdrive4 encrypted mount to avoid bans and the `move.service` use the `gcrypt` mount to upload your new stuff.

Happy to explain in more detail if pull request hasn't yet been accepted.

**Comment by Admin9705** [comment]
good job, made the change :D

**Comment by Deiteq** [comment]
forgot to change some of the text in part of the rclone config crypt instructions, have sent new pull request.
