### ISSUE TITLE
Added Emby into Docker

### ISSUE THREAD

**Issue by Deiteq** [Admin9705/The-Awesome-Plex-Server#30]
I've made another pull request for those that fancy using Emby alongside Plex.
I am new to Emby and am still trying to figure it all out, it is better at transcoding subtitles than Plex, but not so great when it comes to metadata and folder organisation, so I'll be using both depending on whether I need subtitles or not.

**Comment by Admin9705** [comment]
I have emby including a premium pass.  I just never liked the interface.  But in the end, it's about what works :D

**Comment by Admin9705** [comment]
The only thing you have to ensure is how to update it in docker?  Run lots of test.  I took plex out of docker because it refused to update and would crash at time.

**Comment by Deiteq** [comment]
Good point, just tried updating my Emby server and it worked using:-
`sudo docker exec -ti emby update`
I will update the pull request to include it in the commented area.

Agree with you about the interface, Plex is so much more user friendly!

**Comment by Admin9705** [comment]
@Deiteq, how's the plex server running for you? Working great on my end.  I have a rare probelm with the services which i will look more into.  linux is crazy just to get a damn service working properly.

**Comment by Deiteq** [comment]
@Admin9705 to be honest I haven't actually been able to use mine properly yet, still in the process of re-encrypting all my files from encfs to rclone crypt then deleting any unwanted file types and empty folders across 3 google drive accounts as I didn't realise how many useless files I had copied across all three, plus been busy setting up a rpi3 for use with iptv.
Think I've managed to remove the rubbish files now so am running a really slow script (--transfers=1) copying any new files from gdrive1 to gdrive2 then from gdrive2 to gdrive3 then in reverse to make sure each one matches without running the risk of a ban or losing any files via a cheap low powered google compute instance.
Hope to have it all up an running by this weekend if all goes to plan.
In fact, I am now considering having gdrive1 be my upload drive that gets copied over to the other two, gdrive2 for Films and gdrive3 for TV to be used by Plex and Emby, otherwise I'll implement a switch script for Plex so I can quickly swap to another gdrive just in case I ever do get a ban on one of them.

Planning to use Tech Perplexed script for that:-
 [https://techperplexed.blogspot.com.es/2017/04/part-6-making-it-all-come-together.html](url)

Yeah linux can make your head spin, but hopefully I can use some of what I've learnt recently for whatever job I manage to get next!

**Comment by Admin9705** [comment]
what's the purpose using 3 drives @Deiteq, I just have one massive one.

**Comment by daveftw84** [comment]
quick question, whats headphones port?

**Comment by Admin9705** [comment]
Forgot :D

**Comment by Deiteq** [comment]
@Admin9705 , sorry for the delay again, we had some friends stay for a bit, haven't been able to continue with this project.
The 3 drives are backups in case one goes down or gets deleted this has happened twice before....now I'm not taking any chances!

**Comment by Admin9705** [comment]
Hey it’s all good. I’m busy with life also ;)
