### ISSUE TITLE
V4

### ISSUE THREAD

**Issue by Admin9705** [Admin9705/The-Awesome-Plex-Server#35]
@Deiteq , so I have a version 4 branch: https://github.com/Admin9705/The-Awesome-Plex-Server/tree/Version-4

The goal here is to reutilize docker, but to ensure that each container has the ability to update, paths do not have permissions and issues and the tough one is get data to move between sonnar/sab and radarr sab with containers.  

Feel free to make any mods, pulls, and etc.  I'll ensure to put the emby back in there, it's just a copy and paste from v3.

It's good that we went back.  We accomplished fixing the services, understood permission issues, streamlined unionfs, and cleaned up path names.  I think this will make it much easier for docker. 

Issues that I encountered was SAB would download a file, but sonarr would be unable to touch it due to permission issues.  I see you did a great job with docker, figuring out commands and etc.  Just let me know what you think.  I'll be a tad bit slow on this one due to how many projects I have.

Once the docker stuff is done, I believe version 5 should be done with some programming.  Like automating a lot of the install stuff.  Just some ideas.  Any thoughts would help and it's a great learning experience.

**Comment by Deiteq** [comment]
@Admin9705 , well I only did a quick google search for docker emby update and found what was needed, I still don't fully understand docker, but hopefully this time round I will get to grips with it and can help you out!
I'll have a look at version 4 over this week.

**Comment by Admin9705** [comment]
no changes to 4, i'll get it going sometime and when editing; i'll let you
know. it's semi-easy, but a pain.  I reogrganzied everything incase.
