### ISSUE TITLE
videos stuck in completed folders

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/The-Awesome-Plex-Server#36]
for the most part everything moves perfect, once a movie or tv show is done downloading, it moves to drive almost right after but i have about a TB of videos that seemed to slip by and the move service seems to ignore them.. only moving new stuff added.. my 2tb server is stuck averaging at 400GB. last time this happened i ran a command to delete all files and folders inside the folder but with out deleting the main folder.  no big deal just want to figure out how to prevent doing this alot

**Comment by daveftw84** [comment]
sudo rm -rf /mnt/sab/downloads/complete/movies/*
sudo rm -rf /mnt/sab/downloads/complete/tv/*
are the commands if anyone is wondering 

**Comment by daveftw84** [comment]
and sudo rm -rf /mnt/sab/downloads/incomplete/*
 when NOTHING is downloading

**Comment by daveftw84** [comment]
went from 400 gb to 1.6 tb

**Comment by Admin9705** [comment]
It’s couch. It doesn’t always complete files. Switch to radarr. I put couch in the legacy instructions now.  As long as your paths match, your good for the most part. View the Logan in couch also ;)

**Comment by daveftw84** [comment]
So disable or uninstall it?

**Comment by Admin9705** [comment]
We’ll test radarr. Once it works, then disable.

**Comment by daveftw84** [comment]
all i use is the radarr, never use couch
