### ISSUE TITLE
Open Ports

### ISSUE THREAD

**Issue by Chrisly3ear** [Admin9705/The-Awesome-Plex-Server#4]
Another important tip:

If you machine is facing the internet, i.e. it has a public accessible IP address and not a LAN address from a router:
Every `ports: ...` definition in the docker-compose file opens those ports for the public by default!! If you don't want your stuff to be accessible by the public do not use the ports assignment.
Docker's default behaviour is to open the ports also on the iptables firewall.

A solution could be, to define a additional container like an Nginx or Apache container, which proxies all requests to the services. (Like the webinterface you mention)

All the services in the docker-compose are in the same virtual network and can reach each other by service name (or container name, not sure about that). No need for open ports.
So the only external point of entry would be the web server. Everything else is behind it. No open ports to the outside world except 80 and maybe 443.

In Apache the module is called `mod_proxy` and uses the `ProxyPass` and `ProxyPassReverse` directives (https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html).
In Nginx it is, in my opinion easier. There it is just the `proxy_pass` directive, which most of the time is all you'll need (https://www.nginx.com/resources/admin-guide/reverse-proxy/).

Also, if you MUST have ports accessible you can bind it to a internal network interface or just to the local host like so:

```
services:
  whateverservicename:
    image: bestimage/ever:cool
    ports:
      - 127.0.0.1:10000:8080
    ...
```

The service "whateverservicename" would then be reachable under port 10000, but only from localhost.

Chris

P.S.: Also, the "network_mode: host" is probably not needed. Just define the ports Plex needs. The advantage is, that the Plex container would be in the same virtual network than all the other services and they can talk to each other without going out the virtual network and back in.

See here: https://github.com/plexinc/pms-docker#bridge-networking . Yes, it's not one of the two "easy" options, but to me it is clearly the better option.

**Comment by Admin9705** [comment]
Hey that's awesome.  I'll test it out and then incorporate it.  The server is just a media server, but with other people running it; security is important.  Good write up and thank you for putting the time into it.
