### ISSUE TITLE
Feedback?

### ISSUE THREAD

**Issue by townsmcp** [Admin9705/The-Awesome-Plex-Server#6]
Hi
Im not sure if your looking for feedback, however I though I would leave this in case you are.

Great set of instructions. I am following through it at the moment as I havent been able to find anything doing exactly what I want for a tutorial.

Also, just to let you know, line 83 of guide 3 should be changed. The text reads "sudo /etc/init.d/rc.local start" however it should be "sudo /etc/rc.local start" if its following the instructions from above the entry.

Also I'm curious as to why:
1. Your using black hole to shift data between Sonarr and Sab and CP? Isn't it better to direct talk all the systems to get live feedback when stuff is done?
2. Why does Sonarr have its own sab instance and CP its own?

I'm not criticising both of these points but I'm genuinely curious as to the logic - I try and learn something new every day (and today I have learnt a ton of stuff from you so thank you for that). 

I also found I had to grant permission to not prompting for password to enable the reboot and rclone script to run:

"sudo visudo"
at the bottom of the file I had to add the following line
"username ALL = NOPASSWD: /usr/bin/rclone, /opt/rclone.sh

**Comment by Admin9705** [comment]
I'll make the fix.  Feedback is always great.  The reason why I have their own instances is to prevent problems; plus if one crashes... the other one continues to work.  It's a thing I learned to use overtime.  Also if both have a big backlog, you don't have to wait forever for all the shows to upload, while the movies are jumping ahead of the queue.  I tried getting the API to work with the paths and never could, so the blackhole method was simplest.  If you get it working, let me know.  If you find anything else, continue to post.  I'm just glad it's a baseline document to help anyone else.

**Comment by townsmcp** [comment]
Cool. That makes sense. 
I have finished all installs but one set of things remains a mystery to me still - Portainer. Do you intend to put up a quick guide on what to do/how to configure that? I've tried adding new end points of the ports for each container but no joy. 

I'm considering changing the plexdrive reference on the YML from:

     - /mnt/plexdrive5/zilch/:/media
to
     - /mnt/rclone/zilch/:/media
as a temporary messaure. Plex had read in my movies (970 odd) and only 30 TV shows. It seems to be stuck at this point. I've rebooted the entire box, changed to point to plexdrive 4 but all no joy. After Plex is up to date with the library I will then switch back to plexdrive from rclone. 

I must say, my performance of playing media is up and down - to display show details on a device (Amazon FireTV that is hard wired) takes 5 to 10 seconds to load up the details. However as soon as I press play the show instantly plays - much much faster than Amazon Prime and Netflix. Also skipping forward, backward, pausing etc is just as instant. 
My setup is a Lenovo i7 dual core, 8gb ram, 500gb ssd

**Comment by townsmcp** [comment]
lol that didnt work. Setting it to rclone caused it all to crash when starting the script up.

Apart from not showing up all items in Plex when doing a scan, when I now browse to any subfolders in /mnt/plexdrive4 (after setting everything back and rebooting), a new file browser session is spawed but I cant drill into the subfolders. I am going to try deleting the plexdrive cache and rebuilding it to see if this works.
However, it has got me thinking - the plexdrive cache seems to exist only once even though we have plexdrive4 and plexdrive5 running. It is located at ./root/.plexdrive/cache.bolt and im wondering if both 4 and 5 are trying to use the same cache file? If so, is this really recommended? Im going to post something on the PlexDrive threads to see what people think about using the same cache file. Otherwise it might mean just adding a new option to the plexdrive file for "--cache-file string"

**Comment by Admin9705** [comment]
Don't DRILL into the FOLDERS.  It's because it will never load.  Just type it.  Like I type

/media/tv
/media/movies

and that's it.  if you try to load it, good luck.  Try that if you kept the name the same for the YML paths.

**Comment by Admin9705** [comment]
Made tons of changes, hope it helps
