### ISSUE TITLE
s0me m0vies n0t importing 

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/The-Awesome-Plex-Server#8]
m0st 0f the time c0uch p0tat0 d0es a g00d j0b renaming and imp0rting vide0s int0 cl0ud but t0day i had ab0ut 20 vide0s sitting inside the /sabcomplete/ f0lder. i tried f0rcing CP int0 updating the library but it refuses t0 pick up m0vies in /sabcomplete/ and start imp0rting. 
l0gs sh0w n0 err0rs in CP, 
i have it set "t0" m0vies
"fr0m" /sabcomplete/

ive been f0rced int0 manual imp0rting with radarr.
is there a way t0 f0rce radarr t0 aut0 imp0rt, like s0narr d0es?

**Comment by daveftw84** [comment]
s0rry ab0ut the zer0s , this keyb0ard is busted

**Comment by Admin9705** [comment]
goto portainer http://ipv4address:9000 and go to couch potato.  look for the console.  when in the couch potato console, type cd sabcomplete && ls - if you see movies your good and it's couch acting stupid. it does sometimes.  if you don't, might be some unknown error. i just did as a test.

**Comment by daveftw84** [comment]
i havent set up p0rtainer yet. tbh i d0nt kn0w h0w

**Comment by daveftw84** [comment]
i f0und 0ut my m0unt p0int was br0ken and radarr was m0ving vide0s int0 a f0lder called m0ves 0n my server. i restarted server but n0w im missing al0t 0f mem0ry. i d0nt kn0w where the vide0s are hiding n0w and m0vies f0lder is p0inting t0 m0unt p0int n0w

**Comment by daveftw84** [comment]
ty f0r all y0ur help

**Comment by daveftw84** [comment]
i w0uld l0ve t0 invite y0u in server f0r a quick l00k, if y0ure willing

**Comment by Admin9705** [comment]
before doing that, did you execute the YML instructions in the guide?  If you did, then portainer is setup for you.  You just have to goto your http://ipv4address.com:9000 or if local, http://127.0.0.1:9000 - follow the guide on it. portainer is an interface for all of your containers. i'm working another solution for syncing stuff right now that may  (to get around the google upload ban of 750G per day)
