### ISSUE TITLE
03 - PlexDrive 4 (Recommended) - getting plexdrive4 to work

### ISSUE THREAD

**Issue by Deiteq** [Admin9705/The-Awesome-Plex-Server#9]
Hi again Admin9705,
I did another fresh install and managed to get plexdrive4 to work by adding 'allow_other' into line 54 and I used 'uid/gid=1000' plus made `/opt/plexdrive4.sh` executable if that is what you meant?
`screen sudo plexdrive4 --uid=1000 --gid=1000 -o allow_other -v 2 --refresh-interval=1m /mnt/plexdrive4`

I found that Qwatuz answer at [https://github.com/dweidenfeld/plexdrive/issues/70](url) helped a lot and I can see in the plexdrive4.service script you have `allow_other` included.

But unfortunately the plexdrive4.service is `inactive (dead)` again.
I really can't understand why it worked the last time I did a fresh install?

I'm curious about line 67 where it's necessary to remove `/mnt/plexdrive4/zilch` when I don't see anywhere on the scripts that `zilch` gets mounted, would it not affect the google drive folder?
Plus would it cause issues when I start using encfs and unionfs with it?

Sorry for all the questions, in the meantime now that I'm home again I can try using virtualbox to get it all working rather than using JuiceSSH from my note pro into my server!

**Comment by Deiteq** [comment]
Managed to get it working finally by changing the `/opt/plexdrive4.sh` script by adding `nonempty` and `zilch` to line 68.
`plexdrive4 --uid=1000 --gid=1000 -o allow_other nonempty -v 2 --refresh-interval=1m /mnt/plexdrive4/zilch`

I will let you close this issue just in case you want to answer or need to update your script details for others who may run into the same issue as me.
Thanks.

**Comment by Admin9705** [comment]
hey awesome, the reason I had it remove was because an object would float there, but you solved it with the nonempty @Deiteq - was forgetting about that.  I'll update the script. thanks always for your help :D

**Comment by Deiteq** [comment]
Hey @Admin9705 !
My Plex username is Fayly.
Ooof yeah, mental weather over there....I don't really watch TV or read the news so not fully aware of what's happening around the world.
I'll keep checking out your reddit link for any updates, I'm currently trying to transfer my main gdrive encfs folders to rclonecrypt as I've just bought 2 edu accounts that I am now going to use solely for plex and emby, one drive will be linked for movies and the other for tv shows, but both will have movies and tv shows synced with my main drive for all the new downloads so if one account gets banned I could switch mount point and hopefully not have to rescan any library’s! 

I tried to make an emby docker but I can't seem to get my head round it, every example I look at shows stuff for webhosting and such. 
I'm still a major noob in the linux world, would love a simple script to run on a new server that will install all the important stuff like fail2ban, ufw, plex, emby, rclone, plexdrive, pia vpn (for the odd occasion I need to use torrents), all the Usenet stuff, unionfs, lets encrypt and all you will need to do is input account details and authorisation codes for the relevant apps and be done with it.
It seems as though every tutorial out there uses slightly different paths and folder names which just adds to the confusion.
Yours is so far the best, normally try to follow gesis on PlexACD but the plexdrive instructions make it super confusing.

**Comment by Admin9705** [comment]
@Deiteq sent a friend request

**Comment by Deiteq** [comment]
Hey @Admin9705 
Thanks for that, will do the same for you as soon as I figure out how to implement the rclone crypt method into your scripts.
